package dev.catbit.mosaic.client.ui.sdui.implementations.event.events.theme.set_theme

import androidx.compose.material3.ColorScheme
import dev.catbit.mosaic.client.extensions.toColor
import dev.catbit.mosaic.client.ui.sdui.foundation.events.EventRunner
import dev.catbit.mosaic.client.ui.sdui.foundation.events.EventRunningScope
import dev.catbit.mosaic.client.ui.theme.MosaicColors
import dev.catbit.mosaic.core.data.schemas.event.events.theme.SetThemeEventSchema
import dev.catbit.mosaic.core.data.schemas.event.trigger.EventTriggers

object SetThemeEventRunner : EventRunner<SetThemeEventSchema> {
    override suspend fun EventRunningScope.runEvent(event: SetThemeEventSchema) {
        with(event) {
            get<MosaicColors>().setColorSchemes(
                lightColorScheme = ColorScheme(
                    colorsScheme.lightColorScheme.primary.toColor(),
                    colorsScheme.lightColorScheme.onPrimary.toColor(),
                    colorsScheme.lightColorScheme.primaryContainer.toColor(),
                    colorsScheme.lightColorScheme.onPrimaryContainer.toColor(),
                    colorsScheme.lightColorScheme.inversePrimary.toColor(),
                    colorsScheme.lightColorScheme.secondary.toColor(),
                    colorsScheme.lightColorScheme.onSecondary.toColor(),
                    colorsScheme.lightColorScheme.secondaryContainer.toColor(),
                    colorsScheme.lightColorScheme.onSecondaryContainer.toColor(),
                    colorsScheme.lightColorScheme.tertiary.toColor(),
                    colorsScheme.lightColorScheme.onTertiary.toColor(),
                    colorsScheme.lightColorScheme.tertiaryContainer.toColor(),
                    colorsScheme.lightColorScheme.onTertiaryContainer.toColor(),
                    colorsScheme.lightColorScheme.background.toColor(),
                    colorsScheme.lightColorScheme.onBackground.toColor(),
                    colorsScheme.lightColorScheme.surface.toColor(),
                    colorsScheme.lightColorScheme.onSurface.toColor(),
                    colorsScheme.lightColorScheme.surfaceVariant.toColor(),
                    colorsScheme.lightColorScheme.onSurfaceVariant.toColor(),
                    colorsScheme.lightColorScheme.surfaceTint.toColor(),
                    colorsScheme.lightColorScheme.inverseSurface.toColor(),
                    colorsScheme.lightColorScheme.inverseOnSurface.toColor(),
                    colorsScheme.lightColorScheme.error.toColor(),
                    colorsScheme.lightColorScheme.onError.toColor(),
                    colorsScheme.lightColorScheme.errorContainer.toColor(),
                    colorsScheme.lightColorScheme.onErrorContainer.toColor(),
                    colorsScheme.lightColorScheme.outline.toColor(),
                    colorsScheme.lightColorScheme.outlineVariant.toColor(),
                    colorsScheme.lightColorScheme.scrim.toColor(),
                    colorsScheme.lightColorScheme.surfaceBright.toColor(),
                    colorsScheme.lightColorScheme.surfaceDim.toColor(),
                    colorsScheme.lightColorScheme.surfaceContainer.toColor(),
                    colorsScheme.lightColorScheme.surfaceContainerHigh.toColor(),
                    colorsScheme.lightColorScheme.surfaceContainerHighest.toColor(),
                    colorsScheme.lightColorScheme.surfaceContainerLow.toColor(),
                    colorsScheme.lightColorScheme.surfaceContainerLowest.toColor(),
                    colorsScheme.lightColorScheme.primaryFixed.toColor(),
                    colorsScheme.lightColorScheme.primaryFixedDim.toColor(),
                    colorsScheme.lightColorScheme.onPrimaryFixed.toColor(),
                    colorsScheme.lightColorScheme.onPrimaryFixedVariant.toColor(),
                    colorsScheme.lightColorScheme.secondaryFixed.toColor(),
                    colorsScheme.lightColorScheme.secondaryFixedDim.toColor(),
                    colorsScheme.lightColorScheme.onSecondaryFixed.toColor(),
                    colorsScheme.lightColorScheme.onSecondaryFixedVariant.toColor(),
                    colorsScheme.lightColorScheme.tertiaryFixed.toColor(),
                    colorsScheme.lightColorScheme.tertiaryFixedDim.toColor(),
                    colorsScheme.lightColorScheme.onTertiaryFixed.toColor(),
                    colorsScheme.lightColorScheme.onTertiaryFixedVariant.toColor(),
                ),
                darkColorScheme = ColorScheme(
                    colorsScheme.darkColorScheme.primary.toColor(),
                    colorsScheme.darkColorScheme.onPrimary.toColor(),
                    colorsScheme.darkColorScheme.primaryContainer.toColor(),
                    colorsScheme.darkColorScheme.onPrimaryContainer.toColor(),
                    colorsScheme.darkColorScheme.inversePrimary.toColor(),
                    colorsScheme.darkColorScheme.secondary.toColor(),
                    colorsScheme.darkColorScheme.onSecondary.toColor(),
                    colorsScheme.darkColorScheme.secondaryContainer.toColor(),
                    colorsScheme.darkColorScheme.onSecondaryContainer.toColor(),
                    colorsScheme.darkColorScheme.tertiary.toColor(),
                    colorsScheme.darkColorScheme.onTertiary.toColor(),
                    colorsScheme.darkColorScheme.tertiaryContainer.toColor(),
                    colorsScheme.darkColorScheme.onTertiaryContainer.toColor(),
                    colorsScheme.darkColorScheme.background.toColor(),
                    colorsScheme.darkColorScheme.onBackground.toColor(),
                    colorsScheme.darkColorScheme.surface.toColor(),
                    colorsScheme.darkColorScheme.onSurface.toColor(),
                    colorsScheme.darkColorScheme.surfaceVariant.toColor(),
                    colorsScheme.darkColorScheme.onSurfaceVariant.toColor(),
                    colorsScheme.darkColorScheme.surfaceTint.toColor(),
                    colorsScheme.darkColorScheme.inverseSurface.toColor(),
                    colorsScheme.darkColorScheme.inverseOnSurface.toColor(),
                    colorsScheme.darkColorScheme.error.toColor(),
                    colorsScheme.darkColorScheme.onError.toColor(),
                    colorsScheme.darkColorScheme.errorContainer.toColor(),
                    colorsScheme.darkColorScheme.onErrorContainer.toColor(),
                    colorsScheme.darkColorScheme.outline.toColor(),
                    colorsScheme.darkColorScheme.outlineVariant.toColor(),
                    colorsScheme.darkColorScheme.scrim.toColor(),
                    colorsScheme.darkColorScheme.surfaceBright.toColor(),
                    colorsScheme.darkColorScheme.surfaceDim.toColor(),
                    colorsScheme.darkColorScheme.surfaceContainer.toColor(),
                    colorsScheme.darkColorScheme.surfaceContainerHigh.toColor(),
                    colorsScheme.darkColorScheme.surfaceContainerHighest.toColor(),
                    colorsScheme.darkColorScheme.surfaceContainerLow.toColor(),
                    colorsScheme.darkColorScheme.surfaceContainerLowest.toColor(),
                    colorsScheme.darkColorScheme.primaryFixed.toColor(),
                    colorsScheme.darkColorScheme.primaryFixedDim.toColor(),
                    colorsScheme.darkColorScheme.onPrimaryFixed.toColor(),
                    colorsScheme.darkColorScheme.onPrimaryFixedVariant.toColor(),
                    colorsScheme.darkColorScheme.secondaryFixed.toColor(),
                    colorsScheme.darkColorScheme.secondaryFixedDim.toColor(),
                    colorsScheme.darkColorScheme.onSecondaryFixed.toColor(),
                    colorsScheme.darkColorScheme.onSecondaryFixedVariant.toColor(),
                    colorsScheme.darkColorScheme.tertiaryFixed.toColor(),
                    colorsScheme.darkColorScheme.tertiaryFixedDim.toColor(),
                    colorsScheme.darkColorScheme.onTertiaryFixed.toColor(),
                    colorsScheme.darkColorScheme.onTertiaryFixedVariant.toColor(),
                ),
            )
            onTrigger(EventTriggers.onSuccess())
        }
    }
}
